title:              Mark Brown
email:              allenmarkbrown@gmail.com
description:        Software Programming, Python, Django, Git, Pandas,
                    Occasional Home Improvement Projects
                    Occassional Baking
author:             Mark Brown
baseurl:            ""
url:                "https://bethanybeachbum.github.io"

# Social Profiles
twitter_username:   allenmarkbrown
github_username:    bethanybeachbum
facebook_username:  allenmarkbrown@gmail.com  
instagram_username: allenmarkbrown
linkedin_username: bethanybeachbummer@yahoo.com

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

