# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
