title:              Smart Circular Construction Ecosystems
email:              y.yu-1@utwente.nl
description:        The theory of designing a circularity information platform
author:             Yifei Yu
baseurl:            "/SCCE"
url:                "https://yifei-yu-utwente.github.io" 

# Social Profiles
github_username:    Yifei-Yu-UTwente
linkedin_username:  in/yifei-yu-375246144/
facebook_username:  profile.php?id=100013259350468


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

