title:             Saul Rodriguez
email:             saulrodrigueit@gmail.com
description:       My Blog about Ops and sometimes Dev
author:            Saul Rodriguez
baseurl:           "/blog"
url:               "http://saul-r.github.io"

# Social Profiles
github_username:   Saul-R
linkedin_username: bettercallsaul

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate


exclude: ['_site', '.idea']