title:              Madhusudan Upadhyay
email:              
description:        IT Professional
author:             Madhusudan Upadhyay
baseurl:            ""
url:                "https://github.com/adwithme/blog.git"

# Social Profiles
twitter_username:   meupadhyay
github_username:    
facebook_username:  madhusudanupadhyay.com.np
instagram_username:  meupadhyay
linkedin_username: meupadhyay


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
