title:              The Data Analysts
email:              
description:        SF crime data
author:             Paulo Gonzalez
baseurl:            "/"
url:                "https://pauloog.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# remote_theme: pages-themes/merlot@v0.2.0
theme: minima
plugins:
  - jekyll-feed
  
  #- jekyll-remote-theme # add this line to the plugins list if you already have one

# Build settings
#markdown:           kramdown
#paginate:           5
#paginate_path:      "/posts/page:num/"
#plugins:
#  - jekyll-feed
#  - jekyll-paginate
  #- jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
