title:              Objectively Disorienting Language
email:              your-email@example.com
description:        The journey of a junior programmer
author:             Mei Chu
baseurl:            ""
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    BlackrockDigital
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
