# Site settings
title: Clean Blog
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]