title:              Jackson Peoples
email:              jacksonapeoples@gmail.com
description:        Data Science Portfolio
author:             Jackson
baseurl:            ""
url:                "https://JacksonPeoples.github.io"

# Social Profiles
twitter_username:   
github_username:    JacksonPeoples
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
