title:              Team Pixel-Gram Blog
email:              jasper.chan@codefor.ca
description:        Welcome to the Team Pixel-Gram blog! This is your one-stop shop to keep up to date with the Code for Canada fellows (C4C) and their progress. Scroll down to read the blog posts or head over to the about page to learn more about the fellows. 
author:             Team Pixel-Gram
baseurl:            "/pixel-gram.github.io"
url:                "https://pixel-gram.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username: 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-160662711-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
